# Generated by Django 4.2.5 on 2023-12-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovieID',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
