# Generated by Django 4.2.5 on 2023-10-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('BirthDate', models.DateField()),
                ('BirthPlace', models.CharField(max_length=50)),
                ('Height', models.FloatField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
