# Generated by Django 5.0 on 2023-12-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actors', '0004_alter_actors_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actors',
            name='userID',
        ),
        migrations.AddField(
            model_name='actors',
            name='actor_id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
