# Generated by Django 5.0 on 2023-12-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actors', '0006_actors_status'),
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='Movies',
            field=models.ManyToManyField(related_name='Actors', to='Movie.movie'),
        ),
    ]
